# Training Configuration

# Data Parameters
data:
  train_data_dir: '/home/vhari/dom_ameen_chi_link/common/SENTINL0/DINOv2/nlst_train_data'
  test_data_dir: '/home/vhari/dom_ameen_chi_link/common/SENTINL0/DINOv2/nlst_test_data'
  labels_file: '/home/vhari/dom_ameen_chi_link/common/SENTINL0/DINOv2/nlst_actual.csv'
  train_patient_scan_count: 1000
  test_patient_scan_count: 200
  check_slice_thickness: false
  train_val_split: 0.8

# Model Parameters
model:
  name: 'DinoVisionTransformerCancerPredictor'
  dinov2_version: 'vits14'  # Options: 'vits14', 'vitb14', 'vitl14', 'vitg14'
  transformer:
    num_layers: 2
    nhead: 8
    dim_feedforward: 1024
    dropout: 0.1
  predictor:
    layers: [256, 128, 1]
    dropout: 0.1
  unfreeze_last_layers: true  # Whether to unfreeze last few layers of DINOv2
  unfreeze_layers: [9, 10, 11]  # Which layers to unfreeze if unfreeze_last_layers is true

# Training Parameters
training:
  batch_size: 1
  num_epochs: 50
  learning_rate: 0.0001
  early_stopping:
    patience: 10
  optimizer:
    name: 'Adam'
    weight_decay: 0.0
  scheduler:
    name: 'ReduceLROnPlateau'
    patience: 2
    factor: 0.5
    min_lr: 1e-7
  loss:
    name: 'BCEWithLogitsLoss'
  gradient_clipping:
    max_norm: 1.0

# Data Augmentation
transforms:
  train:
    - name: 'Resize'
      size: [224, 224]
    - name: 'RandomHorizontalFlip'
    - name: 'RandomRotation'
      degrees: 10
    - name: 'ColorJitter'
      brightness: 0.1
      contrast: 0.1
    - name: 'ToTensor'
    - name: 'Normalize'
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
  test:
    - name: 'Resize'
      size: [224, 224]
    - name: 'ToTensor'
    - name: 'Normalize'
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

# Random Seed
seed: 42

# MLflow Configuration
mlflow:
  experiment_name: 'DINOv2 Cancer Prediction'
  model_name: 'DinoVisionTransformerCancerPredictor' 